# build stage
FROM node:lts-alpine as build-stage
RUN apk add --no-cache git
WORKDIR /app
COPY client/package*.json ./
RUN npm install
COPY client/ .
RUN npm run build


# production stage
FROM nginx:stable-alpine as production-stage
COPY --from=build-stage /app/public /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
